# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ba2a0172ff3de49f68b17a117019b0558df01a7802c9c202586100337986cb945dea181284ef1b2a9a14ad8b980dc6fe613a92b919d8cc782d46a472a25306

test:
  secret_key_base: cfa1f44a934f41b265e3c17afcc10518628f66a4bddd0de9b0dbfd43143aec3dde3579ab5495889d77a7449e1043620c4c3cf622c4845310504e436617a23982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
